#! /bin/sh

pgrep bspswallow || bspswallow &

# bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9

bspc config focused_border_color '#0000ff'

bspc config border_width        4
bspc config window_gap          25

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
