#! /bin/sh

# pgrep bspswallow || bspswallow &

# bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor eDP-1 -d 1 2 3 4 5

bspc config normal_border_color '#2AC3DE'
bspc config focused_border_color '#8B008B'

bspc config border_width        5
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

bspwm_cleanfullscreen &

ntfd &
