#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
unclutter &
picom --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh --hack

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

bspc config focused_border_color '#0047ab'

bspc config border_width        8
bspc config window_gap          25

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

# pgrep bspswallow || bspswallow &

# bspc config focused_locked_border_color '#49a4f8'
# bspc config focused_sticky_border_color '#49a4f8'
# bspc config focused_private_border_color '#49a4f8'
